### ISSUE TITLE
install error: public/all-v2.13-SNAPSHOT.js

### ISSUE THREAD

**Issue by planetoid** [SSilence/selfoss#601] opened 2014-11-26 03:20 UTC
When I tried to install selfoss, I met the error message in the log file:

      Error file_put_contents(/path/to/selfoss/public/all-v2.13-SNAPSHOT.js): 

The file does not exists!

Thanks for your time.

**Comment by jtojnar** [comment] 2015-05-13 18:29
@planetoid Could you close the issue then?

**Comment by niol** [comment] 2015-05-19 08:35
This can be closed: not a bug.

**Closed** 2015-05-19 08:47 UTC
