### ISSUE TITLE
PHP 7.2 compatibility

### ISSUE THREAD

**Issue by PixiBixi** [SSilence/selfoss#983] opened 2017-10-02 19:55 UTC
Hello, when i try to run a simple command for update my feeds : 

```
/usr/bin/php --file /var/www/rss/cliupdate.php
```

Here's the issue : 

```
The (unset) cast is deprecated
an error occured#
```

If you can fix-it, i'm running PHP7.2 and Deb9.

**Comment by jtojnar** [comment] 2017-10-02 20:15
It was fixed in #870. You can use the [development build](https://bintray.com/fossar/selfoss/selfoss-git/_latestVersion#files) for compatibility with PHP 7.2.

**Comment by PixiBixi** [comment] 2017-10-02 20:17
Oh sorry, i didn't found it when i've wrote "unset" on Issues searchbar :/

**Comment by jtojnar** [comment] 2017-10-02 20:19
No problem. It was a part of a larger clean-up of the code. Not very easy to search for.

**Comment by jtojnar** [comment] 2017-10-02 20:23
If you find other incompatibility with PHP 7.2, please let me know. I have yet to find time to upgrade.

**Comment by PixiBixi** [comment] 2017-10-02 20:32
Mmmh, maybe this : 

```
PHP message: The each() function is deprecated. This message will be suppressed on further calls" while reading response header from upstream.
```

(I've tried with a clean install freshly retrieved from the git)

**Comment by jtojnar** [comment] 2017-10-02 20:39
It indeed sounds like an issue, probably from one of the libraries we use. I will try to compile PHP 7.2 and debug it tomorrow.

**Comment by PixiBixi** [comment] 2017-10-02 20:46
Perfect, tell me when its done, cuz my selfoss is broken :D 

Btw, this is my php72-fpm repository : https://deb.sury.org/ :)

**Comment by jtojnar** [comment] 2017-10-03 17:06
It looks like there is another unset cast in the library we use for accessing database. It was fixed in [master](https://github.com/bcosca/fatfree-core/commit/dce9d6e0cb5596004591c1bf7e5867afad411aeb but not yet released. I filed an issue upstream: https://github.com/bcosca/fatfree-core/issues/226

**Comment by jtojnar** [comment] 2017-10-03 17:53
Regarding the second issue, I cannot reproduce it but I found only two occurrences of the `each` function and one of them is not used. Can you try the following change https://github.com/natxet/CssMin/pull/24?

**Comment by jtojnar** [comment] 2017-10-03 18:50
Yet another incompatible dependency, I have not come upon https://github.com/kesar/HTMLawed/pull/16

**Comment by PixiBixi** [comment] 2017-10-08 16:30
Damnit, changes on https://github.com/natxet/CssMin/pull/24 works, thank you very much :)

Miss me RSS so much ahah!

**Comment by jtojnar** [comment] 2017-10-08 16:50
Yes, that is the issue from fatfree. You can try upgrading it as here https://github.com/SSilence/selfoss/tree/php72

**Comment by PixiBixi** [comment] 2017-10-08 20:08
Indeed it works, thank you for your good work 👍

**Closed** 2018-01-01 06:53 UTC
Labels: bug, upstream issue

**Comment by jernst** [comment] 2018-02-24 00:34
Will there be a new official version soon so us PHP 7.2 users don't have to work off the development build?

**Comment by jtojnar** [comment] 2018-02-24 00:41
@jernst Sorry, it has been long overdue. I moved the remaining non-blocking issues to 3.0 milestone and will finish the two remaining issues now, hopefully releasing 2.18 next week.

**Comment by toonn** [comment] 2018-03-05 14:24
What's the progress on this? I'm running into `The (unset) cast is deprecated` errors since an update and I'm not sure if this is the same or a separate issue.

**Comment by jtojnar** [comment] 2018-03-05 16:11
Yes, that was fixed. Sorry for not releasing a new version, I still did not manage to test https://github.com/SSilence/selfoss/pull/995 on all database servers. I have decided to skip it and release 2.18 now.
