### ISSUE TITLE
PHP Fatal error:  Cannot use $this

### ISSUE THREAD

**Issue by nickrickard** [SSilence/selfoss#773] opened 2016-06-02 09:23 UTC
Debian unstable has just upgraded to php7.0.7 (02 Jun). Was running selfoss 2.14 but upgraded to 2.15 and same error occurs.
running cliupdate.php gives error message:
PHP Fatal error:  Cannot use $this as parameter in [selfoss path]/libs/f3/base.php on line 1185
and feeds are not shown on homepage.

It looks like the use of $this might be depreciated in PHP7.1:
https://wiki.php.net/rfc/this_var

**Comment by jtojnar** [comment] 2016-06-02 09:53
This is a duplicate of #767, pull request pending.

**Closed** 2016-06-04 08:49 UTC
