### ISSUE TITLE
Cannot Star/Unstar : Internal Error

### ISSUE THREAD

**Issue by Keyhaku** [SSilence/selfoss#565] opened 2014-09-25 11:58 UTC
Hi,

I've just met a problem with the star/unstar system, see my nginx log, by uncommenting the line
";always_populate_raw_post_data = -1" in php5.ini i've managed to make it work.

According to php manual (http://php.net/manual/en/ini.core.php), this directive is obsolete from php 5.6 (that the version I'm using).

Regards.
## Log

*182 FastCGI sent in stderr: "PHP message: Fatal error: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead"

**Comment by jtojnar** [comment] 2015-03-10 02:39
As temporary fix you can replace line 1757 in [libs/f3/base.php](https://github.com/SSilence/selfoss/blob/master/libs/f3/base.php#L1757)

		if ($error=error_get_last())

with

		$ignored = "Automatically populating \$HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead.";
		if ($error=error_get_last() && isset($error) && $error['message']!==$ignored)

The issue is described in detail in this  [blog post](https://www.bram.us/2014/10/26/php-5-6-automatically-populating-http_raw_post_data-is-deprecated-and-will-be-removed-in-a-future-version/).

Maybe we should also start an issue in https://github.com/bcosca/fatfree

**Comment by jtojnar** [comment] 2017-02-04 23:13
Closing since it was fixed in #664. Please open a new issue when it reappears.

**Closed by jtojnar** 2017-02-04 23:13 UTC
Labels: bug
