### ISSUE TITLE
Debug messages in apache error.log

### ISSUE THREAD

**Issue by cpu2910** [SSilence/selfoss#966] opened 2017-07-18 12:02 UTC
I watched logs in /var/log/apache2/error.log like:
[2017-07-15 17:45:52] selfoss.DEBUG: start fetching source "Golem.de (id: 36)  [] []
[2017-07-15 17:45:52] selfoss.DEBUG: spout successfully loaded: spouts\rss\golem [] []
[2017-07-15 17:45:52] selfoss.DEBUG: fetch content [] []
[2017-07-15 17:45:52] selfoss.DEBUG: minimum date: 2017-07-01 17:45:52 [] []
[2017-07-15 17:45:52] selfoss.DEBUG: start item fetching [] []
[2017-07-15 17:45:52] selfoss.DEBUG: destroy spout object [] []
[2017-07-15 17:45:52] selfoss.DEBUG: cleanup orphaned and old items [] []
[2017-07-15 17:45:52] selfoss.DEBUG: cleanup orphaned and old items finished [] []
[2017-07-15 17:45:52] selfoss.DEBUG: delete orphaned thumbnails [] []
[2017-07-15 17:45:52] selfoss.DEBUG: delete orphaned thumbnails finished [] []
[2017-07-15 17:45:52] selfoss.DEBUG: delete orphaned icons [] []
[2017-07-15 17:45:52] selfoss.DEBUG: delete orphaned icons finished [] []
[2017-07-15 17:45:52] selfoss.DEBUG: optimize database [] []
[2017-07-15 17:45:52] selfoss.DEBUG: optimize database finished [] []

In $selfoss_dir/config.ini the option logger_level is set to 'NONE'
As expected there are no logs in $selfoss_dir/data/logs

switching logger_level to 'ERROR' let the selfoss.DEBUG-logs in apache-error.lg disappear.

System is debian 8 with kernel: 3.16.0-4-amd64
Apache is 2.4.10-10+deb8u9
php is 7.0.20-1~dotdeb+8.2
selfoss is 2.17

**Comment by jtojnar** [comment] 2017-08-02 05:43
Originally reported on [fora](https://selfoss.aditu.de/forum/index.php?id=1266)

I still have no idea how could this happen. Does replacing the handler in `common.php` help?

```diff
@@ -39,10 +39,7 @@
 // init logger
 $log = new Logger('selfoss');
 if ($f3->get('logger_level') !== 'NONE') {
-    $handler = new StreamHandler(__DIR__ . '/data/logs/default.log', $f3->get('logger_level'));
-    $formatter = new LineFormatter(null, null, true, true);
-    $formatter->includeStacktraces(true);
-    $handler->setFormatter($formatter);
+    $handler = new Monolog\Handler\NullHandler();
     $log->pushHandler($handler);
 }
 $f3->set('logger', $log);
```

**Comment by cpu2910** [comment] 2017-08-02 08:11
No, that doesn't change anything in the behaviour.

**Comment by jantman** [comment] 2017-12-05 23:51
Did you ever figure this out? I actually _want_ this, because I'm running selfoss in a Docker container and I don't want any logs written into the container, I want them spewing to STDOUT/STDERR so Docker can handle them...

**Comment by jtojnar** [comment] 2017-12-06 01:16
@jantman Would #1004 work for you?

**Comment by jantman** [comment] 2017-12-06 11:59
@jtojnar Yes, as far as I can tell that would work perfectly!

**Comment by jtojnar** [comment] 2019-08-01 18:14
The issue was caused by Monolog using a stderr handler when no handler was set. It was fixed by https://github.com/SSilence/selfoss/commit/2395a12a357efd4a2f22edd37385f060a1aa52b4.

**Closed by jtojnar** 2019-08-01 18:14 UTC
Labels: bug
