### ISSUE TITLE
Error using PHP 7.4

### ISSUE THREAD

**Issue by ajjackaus** [SSilence/selfoss#1180] opened 2020-04-30 08:28 UTC
I recently upgraded my website to PHP 7.4 and when I load Selfoss I get the following error.
Internal Server Error
Fatal error: Module 'sqlite3' already loaded

If I revert to 7.2 or 7.3 the problem goes away.

**Comment by jtojnar** [comment] 2020-04-30 15:28
Hi, are you running 2.18 or a development build? I am afraid that 2.18 might not work but [development builds](https://github.com/SSilence/selfoss#download) run for me without a hitch on 7.4.

**Comment by ajjackaus** [comment] 2020-04-30 22:41
I am running 2.18. Maybe I should change to a dev build. Many thanks.

 

 

AJ Jack

**Comment by jtojnar** [comment] 2020-05-01 21:25
Closing as a duplicate of https://github.com/SSilence/selfoss/issues/1157.

**Closed by jtojnar** 2020-05-01 21:25 UTC
Labels: bug
