### ISSUE TITLE
a new API endpoint using GET, where RSS browser plugins direct the browser to add a feed to selfoss e.g. myserver.com/selfoss/subscribe/%s where "%s" contains the feed URL to be subscribed

### ISSUE THREAD

**Issue by chr15m** [SSilence/selfoss#363] opened 2013-06-09 07:07 UTC

**Comment by aslmx** [comment] 2016-04-27 07:00
I have come to the point where i really would love this feature too.

Has something changed in the last 3 years? Is it implemented? Is it planned to be implemented?

thx

**Comment by jtojnar** [comment] 2016-04-27 09:31
I will try to implement this the way I mentioned on [#622](https://github.com/SSilence/selfoss/issues/662#issuecomment-105634002).

**Comment by chr15m** [comment] 2016-04-28 02:37
@jtojnar \o/

**Comment by aslmx** [comment] 2016-04-28 16:53
very good. can't wait for it...

**Comment by jtojnar** [comment] 2016-05-12 20:51
Actually, after some experiments with the selfoss front end code, I have decided to code a new front end instead.

**Comment by jtojnar** [comment] 2016-07-04 20:15
Also this is a duplicate of #254

**Comment by aslmx** [comment] 2016-07-20 06:45
Any news on that topic. are you going to merge your changes @jtojnar

**Comment by jtojnar** [comment] 2017-02-05 12:26
Closing as a duplicate.

As for my alternative client, I was actually working on it last month and it is approximately 80 % done but I will probably not have time to finish it, at least until summer.

**Closed by jtojnar** 2017-02-05 12:26 UTC
Labels: feature request
