### ISSUE TITLE
Use Tags as folders

### ISSUE THREAD

**Issue by Offerel** [SSilence/selfoss#1113] opened 2019-07-01 08:39 UTC
After importing a OPML file from Inoreader, it has also imported my folders from Inoreader as Tags. Thats great so far.

But now I have seen that the sources are displayed independently of the tags in the sidebar. 

I wanted to ask if it is possible to use the displayed tags as folders, so that you can expand/collapse the different tags and see the sources underneath that tag in the sidebar, instead of the separate source area.

**Comment by jtojnar** [comment] 2019-07-13 01:48
This is not currently possible.

Also a duplicate of https://github.com/SSilence/selfoss/issues/786

**Closed by jtojnar** 2019-07-13 01:48 UTC
Labels: feature request
