### ISSUE TITLE
Unprintable characters cause problems

### ISSUE THREAD

**Issue by kst83** [SSilence/selfoss#933] opened 2017-05-29 15:20 UTC
Noticed this on the twitter spout, not sure if others have the same problem:
At least with sqlite as the DB selfoss stumbles over posts containing unprintable characters.

For example to remove these in the usertimeline twitter spout simply add the following line of code one line before the return statement the getTitle function:

`$tweet = preg_replace('/[\x00-\x1F\x7F]/u', '', $tweet);`

A better way of handling this would probably be to apply this in a more central place to all incoming content.

**Comment by jtojnar** [comment] 2017-05-29 19:42
Could you provide an example of offending tweet?

**Comment by kst83** [comment] 2017-05-30 09:53
I've noticed the problem with Twitter User "aswonline" yesterday.
The selfoss REST-API doesn't return any posts for it if the result includes the post containing the invisible character.

**Comment by jtojnar** [comment] 2017-05-30 11:16
I changed your replacement to `$tweet = preg_replace('/[\x00-\x1F\x7F]/u', '', $tweet) === $tweet;`

The equality holds for all of 200 most recent tweets so there do not seem to be any control characters.

**Comment by kst83** [comment] 2017-05-30 11:19
Thats strange, as far as my installation is concerned this change fixed the problem.

**Comment by jtojnar** [comment] 2017-05-30 11:23
Did selfoss manage to store the tweets into database? Could you share (a partial) DB dump?

**Comment by kst83** [comment] 2017-05-30 11:32
Please find attached a database dump.
The item with ID 2076 causes the problem.
[selfoss.zip](https://github.com/SSilence/selfoss/files/1038101/selfoss.zip)
You can select it in the API with http://localhost/selfoss/items?&items=1&offset=94

**Comment by jtojnar** [comment] 2017-05-30 13:12
I see what is happening now. The Twitter API returns:

```
Konjunkturmotor brummt: Deutsche Verbraucher sind weiter in Konsumstimmung – trotz… https://t.co/GBgmhMXdn0… https://t.co/amLt4jZxdm
```

After applying the `formatLinks` method, it will be changed to following:

```
4b6f6e6a756e6b7475726d6f746f72206272756d6d743a2044657574736368652056657262726175636865722073696e
K o n j u n k t u r m o t o r   b r u m m t :   D e u t s c h e   V e r b r a u c h e r   s i n 
642077656974657220696e204b6f6e73756d7374696d6d756e6720e280932074726f747ae280a6203c6120687265663d
d   w e i t e r   i n   K o n s u m s t i m m u n g   � � �   t r o t z � � �   < a   h r e f = 
2268747470733a2f2f742e636f2f4742676d684d58646e3022207461726765743d225f626c616e6b222072656c3d226e
" h t t p s : / / t . c o / G B g m h M X d n 0 "   t a r g e t = " _ b l a n k "   r e l = " n 
6f6f70656e6572206e6f7265666572726572223e68747470733a2f2f742e636f2f4742676d684d58646e303c2f613ee2
o o p e n e r   n o r e f e r r e r " > h t t p s : / / t . c o / G B g m h M X d n 0 < / a > � 
80a6203c6120687265663d2268747470733a2f2f742e636f2f616d4c74346a5a78646d22207461726765743d225f626c
� �   < a   h r e f = " h t t p s : / / t . c o / a m L t 4 j Z x d m "   t a r g e t = " _ b l 
616e6b222072656c3d226e6f6f70656e6572206e6f7265666572726572223e68747470733a2f2f742e636f2f616d4c74
a n k "   r e l = " n o o p e n e r   n o r e f e r r e r " > h t t p s : / / t . c o / a m L t 
346a5a78646d3c2f613e
4 j Z x d m < / a > 
```

For some reason, for you, it changes to:

```
4b6f6e6a756e6b7475726d6f746f72206272756d6d743a2044657574736368652056657262726175636865722073696e
K o n j u n k t u r m o t o r   b r u m m t :   D e u t s c h e   V e r b r a u c h e r   s i n 
642077656974657220696e204b6f6e73756d7374696d6d756e6720e280932074726f747ae280a6203c6120687265663d
d   w e i t e r   i n   K o n s u m s t i m m u n g   � � �   t r o t z � � �   < a   h r e f = 
2268747470733a2f2f742e636f2f4742676d684d58646e30e222207461726765743d225f626c616e6b223e6874747073
" h t t p s : / / t . c o / G B g m h M X d n 0 � "   t a r g e t = " _ b l a n k " > h t t p s 
3a2f2f742e636f2f4742676d684d58646e30e23c2f613e80a6203c6120687265663d2268747470733a2f2f742e636f2f
: / / t . c o / G B g m h M X d n 0 � < / a > � �   < a   h r e f = " h t t p s : / / t . c o / 
616d4c74346a5a78646d22207461726765743d225f626c616e6b223e68747470733a2f2f742e636f2f616d4c74346a5a
a m L t 4 j Z x d m "   t a r g e t = " _ b l a n k " > h t t p s : / / t . c o / a m L t 4 j Z 
78646d3c2f613e
x d m < / a >
```

That is, the first byte of the ellipsis is parsed as a part of the link. I cannot reproduce it though, for me the following code returns the first output both on PHP 7.1 and PHP 5.4.

```php
$text = "Konjunkturmotor brummt: Deutsche Verbraucher sind weiter in Konsumstimmung – trotz… https://t.co/GBgmhMXdn0… https://t.co/amLt4jZxdm";
$text = htmlspecialchars($text);
$text = preg_replace("/([\w-?&;#~=\.\/]+\@(\[?)[a-zA-Z0-9\-\.]+\.([a-zA-Z]{2,3}|[0-9]{1,3})(\]?))/i", '<a href="mailto:$1">$1</a>', $text);
$text = str_replace('http://www.', 'www.', $text);
$text = str_replace('www.', 'http://www.', $text);
$text = preg_replace("/([\w]+:\/\/[\w-?&;#~=\.\/\@]+[\w\/])/i", '<a href="$1" target="_blank" rel="noopener noreferrer">$1</a>', $text);

$hex = true;
for ($i = 0; $i < strlen($text); $i++) {
	echo  $hex ? str_pad(dechex(ord($text[$i])), 2, '0', STR_PAD_LEFT) : $text[$i] . ' ';

	if (($i + 1) % 48 === 0 || $i === strlen($text) - 1) {
		if ($hex) {
			$i -= $i % 48 + 1;
		}
		$hex = !$hex;
		echo PHP_EOL;
	}
}
```

**Comment by kst83** [comment] 2017-05-31 09:18
That's strange, if I execute the code you posted the output is the same as yours.
I have no idea how this faulty text ended up in the DB.

**Comment by jtojnar** [comment] 2017-05-31 10:24
I see you use a modified twitter spout, what does your `formatLinks` method contain?

**Comment by kst83** [comment] 2017-05-31 10:28
The Version I used here contains the following:
```
    public function formatLinks($text) {
        $text = preg_replace("/([\w-?&;#~=\.\/]+\@(\[?)[a-zA-Z0-9\-\.]+\.([a-zA-Z]{2,3}|[0-9]{1,3})(\]?))/i","<a href=\"mailto:$1\">$1</a>",$text);
        $text = str_replace("http://www.","www.",$text);
        $text = str_replace("www.","http://www.",$text);
        $text = preg_replace("/([\w]+:\/\/[\w-?&;#~=\.\/\@]+[\w\/])/i","<a href=\"$1\" target=\"_blank\">$1</a>", $text);
        return $text;
    }
```

**Comment by jtojnar** [comment] 2017-06-01 00:32
In #934, I have changed the Twitter spout to use the replacements provided by the Twitter API, hopefully it will eliminate the possibility of this curious bug happening.

**Comment by kst83** [comment] 2017-06-01 09:04
Thanks, looking forward to the next release.

**Comment by jtojnar** [comment] 2017-06-15 22:26
Closing since the pull request #934 have been merged.

**Closed by jtojnar** 2017-06-15 22:26 UTC
Labels: bug
