### ISSUE TITLE
An error occured after update from 2.12 to 2.14

### ISSUE THREAD

**Issue by bennap** [SSilence/selfoss#703] opened 2015-09-05 16:24 UTC
Hi there,
I have installed Selfoss 2.12 in a shared hosting less than a year ago with a sqlite database.
Recently, I have tried to update my Selfoss version from 2.12 to 2.14. Now I can't read anything because I get a blank page with only "an error occured" written.
I switched log level from ERROR to DEBUG and I can get this following : 

```
09-05-15 18:20:43 Debug set cookie on XXXX expiring in 2592000 seconds
09-05-15 18:20:43 Debug logged in using valid session
09-05-15 18:20:43 Debug Establish database connection
09-05-15 18:20:43 Error Invalid argument supplied for foreach()

```

Since I'm looking for ansmwers, I can get back Selfoss with a new sqlite database but not with the one from the beginning.

Please someone could help me to debug this?

**Comment by bennap** [comment] 2015-09-06 00:15
When I set DEBUG value to 1 in ./common.php, I get this : 
`an error occured: Invalid argument supplied for foreach() /datas/vol3/w4a153566/var/www/flux.avet.fr/htdocs/daos/sqlite/Database.php:47 /datas/vol3/w4a153566/var/www/flux.avet.fr/htdocs/daos/Database.php:31 /datas/vol3/w4a153566/var/www/flux.avet.fr/htdocs/daos/Tags.php:31 /datas/vol3/w4a153566/var/www/flux.avet.fr/htdocs/controllers/Index.php:39 /datas/vol3/w4a153566/var/www/flux.avet.fr/htdocs/index.php:97`

**Comment by niol** [comment] 2015-09-06 09:27
Please remove to ```@``` in ```daos/sqlite/Database.php``` and tell me if you get more info.

If that does not give anything more and if it's possible for you, make your broken sqlite file available for me to debug.

**Comment by bennap** [comment] 2015-09-06 12:33
I have remove `@`in `daos/sqlite/Database.php` line 45 and I get this : `an error occured: Fatal error: Class 'daos\sqlite\F3' not found`

**Comment by niol** [comment] 2015-09-08 11:31
It seems your sqlite file is broken. It seems there are some ways to recover the data from it, for instance http://techblog.dorogin.com/2011/05/sqliteexception-database-disk-image-is.html .

Regarding a selfoss bug, I cannot fix if I cannot reproduce. In order to reproduce, I need a backup of your sqlite file from _before_ your upgrade attempt. Otherwise, I can't fix anything. Good luck.

**Comment by jtojnar** [comment] 2017-02-04 23:56
Closing. If someone encounters this issue again please open a new issue.

**Closed by jtojnar** 2017-02-04 23:56 UTC
