### ISSUE TITLE
Duplicate feed items with "golem" and "heise" types

### ISSUE THREAD

**Issue by monreal** [SSilence/selfoss#418] opened 2013-08-27 15:58 UTC
I often get duplicate feed items using the "golem news" and "heise news" types. If it happens, the dupes appear right after the original. There is no change (spelling etc) as far as I can see.

I also get dupes with the OSNews feed [1] but maybe this is another issues.

[1] http://www.osnews.com/files/recent.rdf

**Comment by niol** [comment] 2015-05-19 08:49
Is this still an issue?

**Comment by f3bruary22** [comment] 2015-05-19 16:33
Duplicates are not an issue for me anymore since I made sure only 1 client performed the update. But then I never used golem or heise

**Comment by jtojnar** [comment] 2017-02-05 12:12
Closing due to clean-up. If you are still able to reproduce it, please open a new issue.

**Closed by jtojnar** 2017-02-05 12:12 UTC
Labels: bug
